apiVersion: v1
kind: Service
metadata:
  name: clickhouse
spec:
  type: {{ .Values.service.type }}
  selector:
    app: clickhouse
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9000
