apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clickhouse
  namespace: prod
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/clickhouse
      sourceRef:
        kind: GitRepository
        name: outback-uptime
        namespace: flux-system
  values: {}
