apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev
  namespace: flux-system
spec:
  interval: 10m
  path: ./flux/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: outback-uptime
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod
  namespace: flux-system
spec:
  interval: 10m
  path: ./flux/overlays/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: outback-uptime
