apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ingest-api
  template:
    metadata:
      labels:
        app: ingest-api
    spec:
      containers:
        - name: ingest-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
