apiVersion: v1
kind: Service
metadata:
  name: ingest-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ingest-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
